server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: sample-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: json-logs
          __path__: /var/logs/*.json

    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            message: message
            module: module
      - labels:
          level
          module
      - timestamp:
          source: time
          format: RFC3339








# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0

# positions:
#   filename: /tmp/positions.yaml

# clients:
#   - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: sample-logs
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: json-logs
#           __path__: /var/logs/*.json
