name: Docker Compose CI/CD

on:
  push:
    branches:
      - main  # or master, based on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run containers
        run: |
          docker-compose -f docker-compose.yml up -d --build
